### ISSUE TITLE
Re-organization

### ISSUE THREAD

**Issue by e3betht** [fempire/women-tech-speakers-organizers#182]
Would you be interested in having the data split out into separate files and folders to make it a bit easier to sort and view just the areas you are looking for? For instance, having a speaker directory with a US file and a Canada file, etc.? I'm happy to do the restructuring, but wanted to know if this was of interest to you first.

**Comment by mlvandijk** [comment]
Alternatively, how about a file per person, marked as part of different categories (i.e. if both speaker and organizer) to prevent duplication? Although this would make the setup more complicated.
