### ISSUE TITLE
Require consent or direct opt-in

### ISSUE THREAD

**Issue by IrisClasson** [fempire/women-tech-speakers-organizers#251]
I'm a big fan of this repository and its intentions, but it was brought to my attention that women can be added to the list without their consent. I suggest that we require direct opt-in or written consent (by for example email), as lists like this one are often used for targeted harassment and we generally want to encourage a consent-first practice. 

I'm one of the directors on the .NET Foundation board of directors and involved with the outreach and diversity action group, and we would love to be able to recommend this site as a place to find female mentors, speakers and more- but we also want to be careful with recommending lists where the people on the list have not opted in or consented to be added.

I understand that it can be difficult to gather consent after the fact (but it is doable), but maybe at least we can start by requiring that a new person has consented or opted-in.

This would also help following the GDPR and similar directives and laws regarding data collection, privacy and managing data to avoid future issues and encourage good practices. 

Fantastic work, and what an incredible list of amazing people!

**Comment by siakaramalegos** [comment]
That's a great point. I think it would be better to convert this to a database with a web front end, and the email used has to be the same as the person being added.
