### ISSUE TITLE
Instructions for adding speaker/organizer info using "edit this page" on GitHub directly.

### ISSUE THREAD

**Issue by sarah11918** [fempire/women-tech-speakers-organizers#327]
Hi @jlooper ! If you'd like, I'd be happy to contribute to the contributing document with instructions for adding an entry to the README via editing the page on GitHub directly.

I maintain similar kinds of instructions [for the open source project I maintain](https://astro-docs-docs.netlify.app/first-time/4-edit-single-page/#edit-this-page-via-github) and also [in a guide on my personal site](https://rainsberger.ca/blog/contribute-open-source-docs-edit-page-on-github/) for contributors to our documentation site where often people are just making very small content edits. Often, just doing this in the browser is sufficient for those kinds of changes, especially when people aren't necessarily looking to maintain a fork (and, that's in fact how I made my own PR last night).

If you're not interested, no worries; just close this issue!  Just offering!

**Comment by ladyleet** [comment]
Yes, please do!
