### ISSUE TITLE
Alphabetize list

### ISSUE THREAD

**Issue by ladyleet** [fempire/women-tech-speakers-organizers#33]
Alphabetize list - seems like we need this now since the list is growing

**Comment by siakaramalegos** [comment]
By first or last name?

**Comment by siakaramalegos** [comment]
Or maybe create a static github page where someone could filter by speaker/mentor/etc and search other things. If someone good at design would make a mockup and style guide (I just hate doing that part), I would build it.

**Comment by siakaramalegos** [comment]
@ladyleet I created a json version of the current list here: 
https://github.com/siakaramalegos/women-tech-speakers-organizers/blob/static-page/src/speakers.json

I could use that to create a basic landing page that is sorted and can be searched/filtered. Lmk if this sounds interesting. It could just be on github pages.

**Comment by ladyleet** [comment]
@siakaramalegos sounds awesome! i'll turn this repo into an org and invite you to it. what framework/lib were you planning on using to build it? @necoline and i were talking about this too and i love the intiative.

**Comment by ladyleet** [comment]
@siakaramalegos here you go. https://github.com/fempire/site-women-tech-speakers-organizers

**Comment by siakaramalegos** [comment]
@ladyleet Cool! I know React best, but I won't be offended if you prefer Angular. Since you're the owner it would make more sense to do it in something you know best.

**Comment by siakaramalegos** [comment]
Oh I haven't actually done anything yet - just played with making the list a json file.

**Comment by ladyleet** [comment]
@siakaramalegos React is fine! It doesn't matter which framework. :)

**Comment by jlooper** [comment]
done, by last name
