### ISSUE TITLE
Clarification about Getting Started

### ISSUE THREAD

**Issue by solace** [fempire/women-tech-speakers-organizers#344]
Hi!

Thank you for creating this incredible resource. :)

Just looking for some clarification about the Getting Started category that I couldn't find in the documentation.

Is this category for people who are new to the industry in terms of career and open to opportunities, mentoring, other. Or who may or may not be new to the industry but are new to the speaking/organising space who want to get involved/experience?

Thanks!

**Comment by jlooper** [comment]
These are folks who are new to the industry and looking for connections
