### ISSUE TITLE
Create a Vue version site for Fempire

### ISSUE THREAD

**Issue by ladyleet** [fempire/women-tech-speakers-organizers#76]
- Please help us create versions of Fempire with the list so we can display it nicely!
- This is also a great way for us to have a cooler "to do app" example in each framework/library

Already created a repo for this - have at it! 
http://github.com/fempire/fempire-vue

**Comment by marti1125** [comment]
could I help you 👍

**Comment by ladyleet** [comment]
@marti1125 sure go ahead and fork the repo, clone it, and submit a PR! :) would love it if this used the vue-cli. :)

**Comment by jlooper** [comment]
I'm so excited to see this done in Vue. What a great potential demo!! Well done. Taking a look!

**Comment by marti1125** [comment]
@ladyleet where is the website =? or where is the resources :smile:

**Comment by ladyleet** [comment]
@marti1125 it has not been created yet!

**Comment by marti1125** [comment]
😮 how to I could get started? 🤔

**Comment by ladyleet** [comment]
just go to the URL and create a site!

**Comment by anfibiacreativa** [comment]
Are you finally working on this. I would love to take part.

**Comment by ladyleet** [comment]
@anfibiacreativa hi! Please feel free to get started!
