### ISSUE TITLE
Create a React version site of Fempire!

### ISSUE THREAD

**Issue by ladyleet** [fempire/women-tech-speakers-organizers#78]
- Please help us create versions of Fempire with the list so we can display it nicely!
- This is also a great way for us to have a cooler "to do app" example in each framework/library

Already created a repo for this - have at it! 
http://github.com/fempire/fempire-react

**Comment by sarahbattey** [comment]
I've SO got this!!! Any particular user stories in mind?

**Comment by ladyleet** [comment]
@sarahbattey nope! feel free to do whatever you please!

**Comment by apennell** [comment]
I'm interested in taking this on if it's still available! ✋
