### ISSUE TITLE
Move Christina Gorton to the readme

### ISSUE THREAD

**Issue by careecodes** [fempire/women-tech-speakers-organizers#88]

**Comment by careecodes** [comment]
@cmgorton I moved you to the README in this PR so that you'll be discoverable in the main body of the project.

Can someone merge? https://github.com/fempire/women-tech-speakers-organizers/pulls

**Comment by jlooper** [comment]
hi, I just want to ensure that we keep everyone alphabetical. Can you verify? thanks

**Comment by careecodes** [comment]
@jlooper Whoops - fixed it.
